# Site settings
title: "Carlo Musolino"
description: "PhD researcher specializing in high-performance computing and GPU-enabled simulations"
theme: minimal

# Optional social media links
github_username: username
twitter_username: carlo_musolino
linkedin_username: carlo-musolino

# Customizations for the theme
show_downloads: true
show_excerpts: true
